# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the add_readme branch
  push:
    branches: [ add_readme ]
  pull_request:
    branches: [ add_readme ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup_jfrog:
      runs-on: ubuntu-latest
      steps:
        - uses: jfrog/setup-jfrog-cli@v2
        - run: jfrog --version
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  create_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
    
  get_file:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact/

    - run: ls -la path/to/artifact/
    
    - run: cat path/to/artifact/world.txt
    
  upload_to_artifactory:
    runs-on: ubuntu-latest
    needs: get_file
    steps: 
      - uses: jfrog/setup-jfrog-cli@v1
        env:
            JF_ARTIFACTORY_1: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJMTmpOeDV2ME9yZkZ6V0xfenh1QmFmNmx4UmZLQzRIdjF4WUdldnd4RFVvIn0.eyJzdWIiOiJqZmZlQDAwMFwvdXNlcnNcL2l2YW4iLCJzY3AiOiJhcHBsaWVkLXBlcm1pc3Npb25zXC9hZG1pbiBhcGk6KiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDAwIiwiaWF0IjoxNjM3NzY5ODUxLCJqdGkiOiJkOGU2YzM2Ni1hM2EzLTRhMGEtOGNiOC1hYzU4ZTFjMjliNmIifQ.HFzinNoKGWs63anaYC0HN_RbkeA9KyGG888rfTATFfkA8rdlxfrx_hjUC798Xo4byntlxqvkwdJBc5aabAfXPWF1E5WkgTRtJp3CpGdyP8Nihy1TLYzv7o_wuxBIE07YDCYFhYBq0fbn3RYXhqjomDkwPt3bEwR6S4MM-zQyRqDiL61lXuXBuuBK8e5pQqlgaBP4KjlYuFVz1Wx8ru5ZYGkfZXQvNlx8guE6t5msm1m4UAjGgiKpPcBsS6pWvtk3zeuRDlWJF7DmLmI-0wCRknA6Bb4YajEGQ0M4vZtWkJKuRL5papNMOKwmPaxP_yau356UrXnvYw-7Kme19SeBYg
      - run: |
          # Ping the server
          jfrog rt ping --access-token JF_ARTIFACTORY_1
